run:
  timeout: 5m
  skip-dirs:
    - vendor/
  # skip-files: # You can add patterns for files to skip
  #  - ".*_test.go"

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15 # Adjust as needed
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120 # Adjust as needed
  goimports:
    local-prefixes: your_project_name_goes_here # Important: set your module prefix
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam # Example: if you often have large structs as params
      - rangeValCopy # Can be noisy with certain patterns
      - singleCaseSwitch # Sometimes a single case switch is fine

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    # - golint # Deprecated, but some still use it. Consider alternatives or specific rules.
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    # - rowserrcheck # Enable if using database/sql
    # - sqlclosecheck # Enable if using database/sql
    - staticcheck
    - stylecheck
    # - testpackage # Enable if you want tests in separate packages
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
  # Disable specific linters if needed, for example:
  # disable:
  #   - exhaustruct

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen # Don't enforce func length on test files
        - gocyclo
    # Example: Exclude a specific linter for a specific path
    # - path: internal/legacy/
    #   linters:
    #     - stylecheck
# Optional: Output configuration
# output:
#   formats:
#     - colored-line-number
#     - json: result.json
#   print-issued-lines: true
#   print-linter-name: true

# Optional: Service configuration for golangci-lint-action
# service:
#   golangci-lint-version: '1.57' # use the same version as in GitHub action
