env: "local" # 'local', 'dev', 'prod'

http_server:
  address: "localhost:8080"
  base_url: "http://localhost:8080" # The base URL for shortened links
  timeout: 5s
  idle_timeout: 60s

telegram:
  # The token is loaded from the .env file or environment variable for security
  token: ${TELEGRAM_TOKEN}

url_shortener:
  alias_length: 4 # The desired length of the short alias
